name: RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  rspec_tests:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: linters

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby Environment
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true

    - name: Run Tests
      run: |
        bundle exec rspec
  
    - name: Run Archived Tests
      run: |
        cd $GITHUB_WORKSPACE/archive/ruby
        bundle exec rspec